### ISSUE TITLE
SocketExceptions 

### ISSUE THREAD

**Issue by dharrigan** [venantius/vim-cljfmt#44]
Hi,

`
Linux daffy 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux`

```
NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.5/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

(although the problem also manifests on latest vim too)

```
% cat profiles.clj           
{:user {:dependencies [[lein-cljfmt "0.6.4"]]
        :plugins [[lein-cljfmt "0.6.4"]
                  [lein-ancient "0.6.15"]
                  [jonase/eastwood "0.3.5"]]}}
```

Using the latest vim-cljfmt via vim Plug.

```
% lein repl
nREPL server started on port 40681 on host 127.0.0.1 - nrepl://127.0.0.1:40681
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
OpenJDK 64-Bit Server VM 11.0.3+4
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e
```

If I start a repl (`lein repl`) in a very simple `hello-world` type of project, then fire up vim and edit a file and do a few `:w`'s, or a few `:reload`'s or even a `:Cljfmt`, the nrepl throws an error:

```
Exception in thread "nRepl-session-4b7391fa-af0d-4bea-90f2-026777df849b" java.net.SocketException: Socket closed
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at nrepl.transport$bencode$fn__450.invoke(transport.clj:116)
	at nrepl.transport.FnTransport.send(transport.clj:41)
	at nrepl.middleware.print$send_nonstreamed.invokeStatic(print.clj:159)
	at nrepl.middleware.print$send_nonstreamed.invoke(print.clj:138)
	at nrepl.middleware.print$printing_transport$reify__841.send(print.clj:174)
	at nrepl.middleware.caught$caught_transport$reify__876.send(caught.clj:58)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__939$fn__945.invoke(interruptible_eval.clj:143)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__1040.invoke(session.clj:175)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Disabling the plugin, removes the problem.

**Comment by venantius** [comment]
Interesting. Let's start by fixing your dependencies - you're using `lein-cljfmt` in deps, which is the plugin. Let's replace that with `cljfmt` and see if that fixes anything.

**Comment by dharrigan** [comment]
Hi,

Thank you for your prompt reply. Changed my `~/.lein/profiles.clj` to this:

```
{:user {:dependencies [[cljfmt "0.6.4"]]
        :plugins [[lein-cljfmt "0.6.4"]
                  [lein-ancient "0.6.15"]
                  [jonase/eastwood "0.3.5"]]}}
```

Started nrepl (lein repl), started vim, loaded a file and did `Cljfmt`, same error:

```
Exception in thread "nRepl-session-bc75778f-fa10-45c5-937a-92a0b3eb1463" 
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at nrepl.transport$bencode$fn__450.invoke(transport.clj:116)
	at nrepl.transport.FnTransport.send(transport.clj:41)
	at nrepl.middleware.print$send_nonstreamed.invokeStatic(print.clj:159)
	at nrepl.middleware.print$send_nonstreamed.invoke(print.clj:138)
	at nrepl.middleware.print$printing_transport$reify__841.send(print.clj:174)
	at nrepl.middleware.caught$caught_transport$reify__876.send(caught.clj:58)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__939$fn__945.invoke(in
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__1040.invoke(session.clj:175)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Did `:messages` in vim and this is the output

```
Error detected while processing function cljfmt#Format:
line   12:
Cljfmt: Failed to format file, likely due to a syntax error.
```

**Comment by venantius** [comment]
Well... _do_ you have a syntax error? What happens if you run cljfmt at the command line?

**Comment by dharrigan** [comment]
Hi,

Perhaps that was it. I'm unable to reproduce it right now, after cleaning things down and rewriting the test to be simple. Can I monitor this for a while and see if it happens again?

**Comment by venantius** [comment]
Sure. If I don't hear from you in a week I'll close this.

**Comment by dharrigan** [comment]
Thank you. That is very kind of you :-) I want to be 100% it was my fubar :-)

**Comment by dharrigan** [comment]
Okay,

So, I have code that is error free, slightly formatted incorrectly, and I get the stack dump with the socket exception. I'll upload the repo to my github account and let you have a look. Here it is. It's a very simple, learning clojure kata.

https://github.com/dharrigan/palindromes

**Comment by venantius** [comment]
I never got the edit notification after you added the repo - just coming back to this now - I'm afraid it works on my machine? Your `src` file seems to be formatted correctly already and your `test` file  auto-corrects without any errors.
